name: base
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.5=pyhd8ed1ab_0
  - backports.zstd=1.3.0=py312h90b7ffd_0
  - blas=1.0=mkl
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - conda=26.1.0=py312h7900ff3_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_1
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.3.1=h171cf75_0
  - distro=1.9.0=pyhd8ed1ab_1
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozendict=2.4.7=py312h4c3975b_0
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py312ha4f8f14_101
  - harfbuzz=12.3.2=h6083320_0
  - hdf5=1.14.6=nompi_h19486de_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libaec=1.1.5=h088129d_0
  - libarchive=3.8.5=gpl_hc2c16d8_100
  - libcurl=8.18.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libglib=2.86.4=h6548e54_1
  - libgomp=15.2.0=he0feb66_17
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.2=hb03c661_0
  - libmamba=2.5.0=hd28c85e_0
  - libmamba-spdlog=2.5.0=h12fcf84_0
  - libmambapy=2.5.0=py312h1ca65c7_0
  - libmpdec=4.0.0=hb03c661_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.55=h421ea60_0
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libuuid=2.41.3=h5347b49_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mamba=2.5.0=h9835478_0
  - menuinst=2.4.2=py312h7900ff3_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py312hacdc0fc_0
  - mkl_fft=2.1.1=py312h8fe796d_0
  - mkl_random=1.3.0=py312h505adc9_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - numpy=2.4.2=py312h08c6c3d_0
  - numpy-base=2.4.2=py312h00548fb_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.1=py312h8ecdadd_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.47=haa7fec5_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py312h4c3975b_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.12=8_cp312
  - readline=8.3=h853b02a_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.5=pyhcf101f3_1
  - ruamel.yaml=0.18.17=py312h5253ce2_2
  - ruamel.yaml.clib=0.2.15=py312h5253ce2_1
  - setuptools=82.0.0=pyh332efcf_0
  - simdjson=4.2.4=hb700be7_0
  - six=1.17.0=pyhe01879c_1
  - spdlog=1.17.0=hab81395_1
  - tbb=2022.3.0=hb700be7_2
  - tbb-devel=2022.3.0=h51de99f_2
  - tk=8.6.13=noxft_h366c992_103
  - tqdm=4.67.3=pyh8f84b5b_0
  - truststore=0.10.4=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - attrs==25.4.0
    - contourpy==1.3.3
    - cssselect2==0.9.0
    - cycler==0.12.1
    - fonttools==4.61.1
    - itk==5.4.5
    - itk-core==5.4.5
    - itk-filtering==5.4.5
    - itk-io==5.4.5
    - itk-numerics==5.4.5
    - itk-registration==5.4.5
    - itk-segmentation==5.4.5
    - joblib==1.5.3
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - matplotlib==3.10.8
    - networkx==3.6.1
    - nibabel==5.3.3
    - nvidia-ml-py==13.590.48
    - nvitop==1.6.2
    - parmap==1.7.0
    - pillow==12.1.1
    - portalocker==3.2.0
    - psutil==7.2.2
    - pydicom==3.0.1
    - pydyf==0.12.1
    - pyparsing==3.3.2
    - pyphen==0.17.2
    - referencing==0.37.0
    - rpds-py==0.30.0
    - scikit-image==0.26.0
    - scikit-learn==1.8.0
    - scipy==1.17.1
    - simpleitk==2.5.3
    - threadpoolctl==3.6.0
    - tifffile==2026.2.24
    - tinycss2==1.5.1
    - tinyhtml5==2.0.0
    - typing_extensions==4.15.0
    - watchdog==6.0.0
    - weasyprint==68.1
    - webencodings==0.5.1
    - xmltodict==1.0.4
    - zopfli==0.4.1

prefix: "/opt/conda"
